### ISSUE TITLE
Koodikatselmointi 1

### ISSUE THREAD

**Issue by perdperd** [schme/Pong#1]
Moi, tässä hieman palautetta koodista! Palaute koskee 2.6.2013 14:51 ladattua projektia.

Ohjelman rakenne vaikuttaa hyvältä ja selkeältä ja koodikin on kokonaisuutena sangen hyvää, joten tämä meni ehkä vähän pilkunviilaukseksi.

Aloitetaan testeistä:

Ensinnäkään Entitylla ei ole lainkaan testiluokkaa. Olisi varmaan syytä luoda luokka EntityTest ja luoda sinne testejä.

BallTestin lopussa kommentoit entityMovesTheCorrectAmountWithSimpleValues():a "Entity.move() test more than a Ball test.", mikä pitääkin paikkansa. Kaikki entityMovesTheCorrectAmountWithSimpleValues() jälkeen tulevat testit ovat pohjimmiltaan Entityn testejä ja ne lienee syytä siirtää EntityTestiin.

BallTestissa ja monessa muussakin testiluokassa testeissä esiintyy usein monta asserttia. Ohjelmistotekniikan menetelmät -kurssilla opetettiin yleensä testaamaan yhdessä testissä vain yhtä asiaa, eli mielellään yhdessä testissä olisi vain yksi assert. Tätä sääntöä ei kyllä tarvitse ehkä ihan kirjaimellisesti noudattaa.

PadTestin testien nimiä voisi ehkä hieman muutella. testLeftPadCorrectCoordinates():n nimestä ei sinällään käy ilmi LeftPadin ja CorrectCoordinates:n yhteys. Sille voisi antaa nimeksi esimerkiksi "testLeftPadHasCorrectCoordinatesAfterCreation()" tai jotain vastaavaa. Vastaavaa nimenmuutosta voisi harkita kaikille metodeille testRightPadCorrectAbsurdBoardSizeCoordinates() asti.

Sitten vielä hieman itse koodista:

Ballin moveWithin2d()-metodi taitaa kääntää pallon turhan aikaisin. Pallo ikään kuin törmää tyhjään ilmaan. Pallo pitää varmaan ensiksi liikuttaa reunalle asti ja sitten negatoida nopeudet.

Board-luokan move()-metodi on jollain tasolla hieman harhaanjohtavasti nimetty, erityisesti koska Entity-luokalla on move()-metodi, joka liikuttaa itse Entitya, joten helposti olettaisi myös Boardin move()-metodin liikuttavan Boardia. Sille voisi antaa uudeksi nimeksi esimerkiksi "moveEntities()".

Projekti on kyllä kokonaisuutena hyvällä mallilla. lwjgl vaikuttaa ihan hauskalta kirjastolta. :)

github crashasi kesken tämän lähetyksen, nice

**Comment by schme** [comment]
Hei!

Palautteesta:

EntityTest todellakin puuttuu, voisin tämän lisätä. Tällä hetkellähän kaikki Entityn testit ovat _BallTest_in sisällä (siksi pääsääntöisesti testit on prefiksattu joko _ball_ tai _entity_ sanalla), mikä ilmenee Javadocistakin. Hieman epäselkeä toteutus tosin ja siirtänen tämän palautteesi mukaiseksi.
Sama koskee useita assertteja. Puskin ennen sunnuntain deadlinea vain kasan testejä, välittämättä sen enempää niiden sijoittelusta. Refaktoroin heti kun ehdin! Konstruktoreiden testitkin nimetään uudelleen.

Olet oikeassa moveWithin2D():stä. Tämä ratkaisu oli nopea implementaatio pallon pitämiseksi boardin sisällä, mikä helpotti testausta. Metodin javadocissa on merkattu TODO tämän korjaamiseksi.

Board luokan move() metodi on hieman jäänne siitä, että tykkään nimetä kutsuvat metodit samalla nimellä: Alue luokka kutsuu metodia sada(), joka kutsuu sisältämiensä Taivas luokkien sada() metodia, joka taas kutsuu sisältämiensä Pilvi luokkien sada() metodeja. Mutta tuostahan ei tässä ole edes kyse, joten nimeäminen on epäselvä. Muutetaan! Etenkin jos haluan joskus liikuttaa Boardia, on tuo hieman hämärä. En varmaankaan olisi edes kiinnittänyt huomiota ilman palautetta.

LWJGL on erittäin hauska kirjasto, suosittelen lämpimästi. Varsinkin jos haluaa opetella puhdasta OpenGL. Helpompi setupata ja tuntuu toimivan luotettavammin kuin esim. C:n SDL -kirjasto (Javalla en ole SDL:ää testannut). Vielä kun netistä löytyisi kunnollista OpenGL materiaalia 3.x:lle, kaikki tuntuu olevan 1.1 versiolle. Itse kirjastolle löytyy paljon materiaalia, en ollut ennen tätä projekia lwjgl:ää käyttänyt.

Kiitos palautteesta! Tämähän on kuitenkin vapaaehtoinen, mutta huomiosi olivat hyviä. Jos voin kysyä, niin kokeilitko buildata ja käynnistää projektia? En ole testannut muulla kuin omalla koneellani, mietin onko Maven edes oikein konffattu.

**Comment by perdperd** [comment]
Yritin kyllä buildata ja käynnistää, mutta lwjgl heitti UnsatisfiedLinkErroria. En osaa sanoa tarkemmin mistä johtuu, maven kyllä lataili paketteja.
